name: Detox
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

env:
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16 # expo-cli preferred
          cache: "yarn"

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: $EXPO_TOKEN

      - name: Install Detox CLI
        run: |
          brew tap wix/brew
          brew install applesimutils
          npm install -g detox-cli

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build App for Detox
        run: detox build -c ios.sim.release

      - uses: futureware-tech/simulator-action@v2
        with:
          model: "iPhone 12"

      - name: Run Detox
        run: detox test -c ios.sim.release
