name: Detox 1
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  do-stuff:
    runs-on: ubuntu-latest
    steps:
      # just get a succuessful workflow
      - uses: actions/checkout
