name: Trigger Secure E2E Workflows
on:
  push:
    branches:
      - main
  # temporarily disable Detox on PR until I have it actually test functionality
  # pull_request:
  #   types: [opened, synchronize, reopened]

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      # just a placeholder to get a succeeding run
      - uses: actions/checkout@v3
